/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyProject1;

import com.sun.glass.events.KeyEvent;
import java.awt.image.BufferedImage;
import java.beans.Statement;
import java.io.File;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import java.text.*;
import java.util.*;
import javax.swing.JFrame;

/**
 *
 * @author SANTOSH
 */
public class Admission extends javax.swing.JFrame {
   static File file;
   
 //   static Connection con;
    Statement stmt;
    PreparedStatement pstmt,pstmt2;
    ResultSet rs;
    /**
     * Creates new form Admission
     */
    public Admission() {
        file=null;
        pstmt=null;
        pstmt2=null;
        rs=null;
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        this.setLocationRelativeTo(null);        
        yearLabel.setText(""+AdminControl.year);
        msgLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        firstnameTextField = new javax.swing.JTextField();
        lastnameTextField = new javax.swing.JTextField();
        father_nameTextField = new javax.swing.JTextField();
        mother_nameTextField = new javax.swing.JTextField();
        mobile_numberTextField = new javax.swing.JTextField();
        homePhoneTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTextArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        genderComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        maritalStatusComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        qualificationComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        tenthPerTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        twelthPerTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ugPerTextField = new javax.swing.JTextField();
        pgPerTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        mainMenuButton = new javax.swing.JButton();
        uploadLabel = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        formNoTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        msgLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        refreshLabel = new javax.swing.JLabel();
        imgLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 255));

        jLabel3.setBackground(new java.awt.Color(0, 102, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("INDIRA NAGAR SARSIWA, DIST - BALODABAZAR-BHATAPARA (C.G.) 493559");
        jLabel3.setOpaque(true);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("       ADMISSION PORTAL       ");
        jLabel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        firstnameTextField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        firstnameTextField.setForeground(new java.awt.Color(153, 153, 153));
        firstnameTextField.setText("FIRST NAME");
        firstnameTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                firstnameTextFieldMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                firstnameTextFieldMouseExited(evt);
            }
        });
        firstnameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                firstnameTextFieldKeyTyped(evt);
            }
        });

        lastnameTextField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lastnameTextField.setForeground(new java.awt.Color(153, 153, 153));
        lastnameTextField.setText("LAST NAME");
        lastnameTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lastnameTextFieldMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lastnameTextFieldMouseExited(evt);
            }
        });
        lastnameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lastnameTextFieldKeyTyped(evt);
            }
        });

        father_nameTextField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        father_nameTextField.setForeground(new java.awt.Color(153, 153, 153));
        father_nameTextField.setText("FATHER'S NAME");
        father_nameTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                father_nameTextFieldMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                father_nameTextFieldMouseExited(evt);
            }
        });
        father_nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                father_nameTextFieldActionPerformed(evt);
            }
        });
        father_nameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                father_nameTextFieldKeyTyped(evt);
            }
        });

        mother_nameTextField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        mother_nameTextField.setForeground(new java.awt.Color(153, 153, 153));
        mother_nameTextField.setText("MOTHER'S NAME");
        mother_nameTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mother_nameTextFieldMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mother_nameTextFieldMouseExited(evt);
            }
        });
        mother_nameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mother_nameTextFieldActionPerformed(evt);
            }
        });
        mother_nameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mother_nameTextFieldKeyTyped(evt);
            }
        });

        mobile_numberTextField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        mobile_numberTextField.setForeground(new java.awt.Color(153, 153, 153));
        mobile_numberTextField.setText("MOBILE NUMBER");
        mobile_numberTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mobile_numberTextFieldMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mobile_numberTextFieldMouseExited(evt);
            }
        });
        mobile_numberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobile_numberTextFieldActionPerformed(evt);
            }
        });
        mobile_numberTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mobile_numberTextFieldKeyTyped(evt);
            }
        });

        homePhoneTextField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        homePhoneTextField.setForeground(new java.awt.Color(153, 153, 153));
        homePhoneTextField.setText("HOME PHONE");
        homePhoneTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homePhoneTextFieldMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homePhoneTextFieldMouseExited(evt);
            }
        });
        homePhoneTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homePhoneTextFieldActionPerformed(evt);
            }
        });
        homePhoneTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                homePhoneTextFieldKeyTyped(evt);
            }
        });

        addressTextArea.setColumns(20);
        addressTextArea.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        addressTextArea.setForeground(new java.awt.Color(153, 153, 153));
        addressTextArea.setLineWrap(true);
        addressTextArea.setRows(5);
        addressTextArea.setText("Correspondence Address");
        addressTextArea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addressTextAreaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addressTextAreaMouseExited(evt);
            }
        });
        jScrollPane1.setViewportView(addressTextArea);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("10 th % - ");

        genderComboBox.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        genderComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Gender - ");

        maritalStatusComboBox.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        maritalStatusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Unmarried", "married" }));
        maritalStatusComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Marital Status - ");

        qualificationComboBox.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        qualificationComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Below Fifth", "Fifth Pass", "Eighth Pass", "Tenth Pass", "Twelth Pass", "UG", "PG", "DR" }));
        qualificationComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Qualification - ");

        tenthPerTextField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        tenthPerTextField.setForeground(new java.awt.Color(153, 153, 153));
        tenthPerTextField.setText("00.00");
        tenthPerTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tenthPerTextFieldMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tenthPerTextFieldMouseExited(evt);
            }
        });
        tenthPerTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tenthPerTextFieldKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("12 th % - ");

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("DOB - ");

        twelthPerTextField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        twelthPerTextField.setForeground(new java.awt.Color(153, 153, 153));
        twelthPerTextField.setText("00.00");
        twelthPerTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                twelthPerTextFieldMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                twelthPerTextFieldMouseExited(evt);
            }
        });
        twelthPerTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                twelthPerTextFieldKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("UG % - ");

        ugPerTextField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        ugPerTextField.setForeground(new java.awt.Color(153, 153, 153));
        ugPerTextField.setText("00.00");
        ugPerTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ugPerTextFieldMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ugPerTextFieldMouseExited(evt);
            }
        });
        ugPerTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ugPerTextFieldKeyTyped(evt);
            }
        });

        pgPerTextField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        pgPerTextField.setForeground(new java.awt.Color(153, 153, 153));
        pgPerTextField.setText("00.00");
        pgPerTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pgPerTextFieldMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pgPerTextFieldMouseExited(evt);
            }
        });
        pgPerTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pgPerTextFieldKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setText("PG % - ");

        jDateChooser.setDateFormatString("d MMM, yyyy");

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1380, 100));

        backButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        backButton.setText("<< BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        mainMenuButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mainMenuButton.setText("MAIN MENU");
        mainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainMenuButton)
                .addGap(115, 115, 115))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        uploadLabel.setBackground(new java.awt.Color(204, 255, 204));
        uploadLabel.setFont(new java.awt.Font("Arial Unicode MS", 0, 18)); // NOI18N
        uploadLabel.setText(" UPLOAD ");
        uploadLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        uploadLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        uploadLabel.setOpaque(true);
        uploadLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uploadLabelMouseClicked(evt);
            }
        });

        submitButton.setBackground(new java.awt.Color(255, 255, 255));
        submitButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        submitButton.setForeground(new java.awt.Color(51, 102, 255));
        submitButton.setText("SUBMIT");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        formNoTextField.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        formNoTextField.setForeground(new java.awt.Color(153, 153, 153));
        formNoTextField.setText("FORM NUMBER");
        formNoTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formNoTextFieldMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formNoTextFieldMouseExited(evt);
            }
        });
        formNoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formNoTextFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formNoTextFieldKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel12.setText("Year -");

        yearLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        yearLabel.setText("jLabel13");

        msgLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        msgLabel.setForeground(new java.awt.Color(255, 0, 0));
        msgLabel.setText("*Form no Already exists");

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));

        jLabel1.setBackground(new java.awt.Color(0, 0, 153));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("OXFORD SPOKEN ENGLISH ACADEMY");

        refreshLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        refreshLabel.setForeground(new java.awt.Color(255, 255, 255));
        refreshLabel.setText("Refresh");
        refreshLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refreshLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(205, 205, 205)
                .addComponent(refreshLabel)
                .addGap(66, 66, 66))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(refreshLabel)
                    .addComponent(jLabel1))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        imgLabel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        imgLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgLabel.setText("upload image here");
        imgLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black, java.awt.Color.black));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(formNoTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(msgLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(547, 547, 547))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(homePhoneTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mobile_numberTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mother_nameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(father_nameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastnameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstnameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(47, 47, 47)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(maritalStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(yearLabel)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(qualificationComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 1, Short.MAX_VALUE)
                                                .addComponent(tenthPerTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                                .addComponent(twelthPerTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ugPerTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(pgPerTextField, javax.swing.GroupLayout.Alignment.LEADING))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(uploadLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(submitButton, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addGap(117, 117, 117))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(92, 92, 92))))))))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(formNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(msgLabel)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                                .addComponent(firstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(genderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maritalStatusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(father_nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(qualificationComboBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mother_nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tenthPerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mobile_numberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(twelthPerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(homePhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ugPerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(pgPerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(submitButton))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(yearLabel)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(imgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(uploadLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void father_nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_father_nameTextFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_father_nameTextFieldActionPerformed

    private void homePhoneTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homePhoneTextFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_homePhoneTextFieldActionPerformed

    private void mother_nameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mother_nameTextFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mother_nameTextFieldActionPerformed

    private void mobile_numberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobile_numberTextFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mobile_numberTextFieldActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        AdminControl.year=2011;
        MainPage mainpage=new MainPage();
        mainpage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void mainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonActionPerformed
        // TODO add your handling code here:
        mainMenuButton.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        AdminControl.year=2011;
        MainPage mainpage=new MainPage();
        mainpage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mainMenuButtonActionPerformed
    
    /**
     * @param fieldname*
     * @param fieldval************************************************************************************/
    public void checkFor(javax.swing.JTextField fieldname,String fieldval){
        if((fieldname.getText().trim()).equalsIgnoreCase(fieldval)){
            fieldname.setText("");
        }
    }
    
    private void firstnameTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstnameTextFieldMouseClicked
        checkFor(firstnameTextField,"FIRST NAME");     
    }//GEN-LAST:event_firstnameTextFieldMouseClicked

    private void addressTextAreaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addressTextAreaMouseClicked
           if((addressTextArea.getText().trim()).equalsIgnoreCase("Correspondence Address")){
               addressTextArea.setText("");
           }               
    }//GEN-LAST:event_addressTextAreaMouseClicked

    private void lastnameTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lastnameTextFieldMouseClicked
        checkFor(lastnameTextField,"LAST NAME");
    }//GEN-LAST:event_lastnameTextFieldMouseClicked

    private void father_nameTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_father_nameTextFieldMouseClicked
        checkFor(father_nameTextField,"FATHER'S NAME");
    }//GEN-LAST:event_father_nameTextFieldMouseClicked

    private void mother_nameTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mother_nameTextFieldMouseClicked
        checkFor(mother_nameTextField,"MOTHER'S NAME");
    }//GEN-LAST:event_mother_nameTextFieldMouseClicked

    private void mobile_numberTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mobile_numberTextFieldMouseClicked
       checkFor(mobile_numberTextField,"MOBILE NUMBER");
    }//GEN-LAST:event_mobile_numberTextFieldMouseClicked

    private void homePhoneTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePhoneTextFieldMouseClicked
        checkFor(homePhoneTextField,"HOME PHONE");
    }//GEN-LAST:event_homePhoneTextFieldMouseClicked

    private void tenthPerTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tenthPerTextFieldMouseClicked
       checkFor(tenthPerTextField,"00.00");
    }//GEN-LAST:event_tenthPerTextFieldMouseClicked

    private void twelthPerTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twelthPerTextFieldMouseClicked
        checkFor(twelthPerTextField,"00.00");
    }//GEN-LAST:event_twelthPerTextFieldMouseClicked

    private void ugPerTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ugPerTextFieldMouseClicked
        checkFor(ugPerTextField,"00.00");
    }//GEN-LAST:event_ugPerTextFieldMouseClicked

    private void pgPerTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pgPerTextFieldMouseClicked
        checkFor(pgPerTextField,"00.00");
    }//GEN-LAST:event_pgPerTextFieldMouseClicked
    
    private void uploadLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uploadLabelMouseClicked
        // TODO add your handling code here:
        uploadLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        try
        {
            JFileChooser chooser=new JFileChooser();
            chooser.setCurrentDirectory(new File("."));     // seting current directory
                       // or
        //      chooser.setCurrentDirectory(new File("desktop"));
            int result = chooser.showOpenDialog(null);

            if (result == JFileChooser.APPROVE_OPTION)
            {
                String file_address =chooser.getSelectedFile().getPath();
                file=new File(file_address);

                if((ImageIO.read(file)==null)) // file type
                    JOptionPane.showMessageDialog(null,"Please select .jpg file only");
                else
                {
                    BufferedImage originalimg=ImageIO.read(file);
                    ImageIcon icon=new ImageIcon(ImageProcessing.myResize(originalimg,imgLabel.getWidth(),imgLabel.getHeight()));
             //  ImageIcon icon=new ImageIcon(ImageProcessing.myResize(originalimg,180,200));
                    imgLabel.setIcon(icon);
                }
            }
            else
            JOptionPane.showMessageDialog(null,"Please Select file");
        }catch(Exception ex){JOptionPane.showMessageDialog(null,ex);}
        uploadLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));    
 
    }//GEN-LAST:event_uploadLabelMouseClicked

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // TODO add your handling code here:
        submitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
    
     //   int formno=0,check_formno=0;
        String year=""+AdminControl.year;
        String formno="0",check_formno="0";
        String fst_name="",lst_name="",f_name=" ",m_name=" ",mobno="",homephone=" ",address=" ",gender=" ",marital_status=" ",qualification=" ";
     //   Float tenth,twelth,ug,pg;
        String tenth,twelth,ug,pg;
        String dob=" ",admit_date=" ";
            
        try{ 
            pstmt=MyLogin.con.prepareStatement("insert into ADMISSION_TABLE(FORM_NO,FIRST_NAME,LAST_NAME,FATHER_NAME,MOTHER_NAME,MOBNO,HOME_PHONE,ADDRESS,GENDER,MARITAL_STATUS,QUALIFICATION,TENTH,TWELTH,UG,PG,DOB,A_YEAR,ADMIT_DATE,S_ID)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            pstmt2=MyLogin.con.prepareStatement("select FORM_NO from ADMISSION_TABLE where FORM_NO=?",ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
        
        formno=formNoTextField.getText().trim();       
        fst_name=(firstnameTextField.getText().trim()).toUpperCase();        
        lst_name=lastnameTextField.getText().trim().toUpperCase();
        f_name=father_nameTextField.getText().trim().toUpperCase();
        m_name=mother_nameTextField.getText().trim().toUpperCase();
        mobno=mobile_numberTextField.getText().trim();    
        homephone=homePhoneTextField.getText().trim();
        address=addressTextArea.getText().toUpperCase();
        gender=(String)genderComboBox.getSelectedItem();
        marital_status=(String)maritalStatusComboBox.getSelectedItem();
        qualification=(String)qualificationComboBox.getSelectedItem();
     /*   tenth=Float.parseFloat(tenthPerTextField.getText());
        twelth=Float.parseFloat(twelthPerTextField.getText());
        ug=Float.parseFloat(ugPerTextField.getText());
        pg=Float.parseFloat(pgPerTextField.getText());  */
        tenth=tenthPerTextField.getText();
        twelth=twelthPerTextField.getText();
        ug=ugPerTextField.getText();
        pg=pgPerTextField.getText();
   //     dob=(String)jDateChooser.getDateFormatString(); 
        Date date = new Date();
		DateFormat df;
		df = DateFormat.getDateInstance(DateFormat.MEDIUM, Locale.UK);
		System.out.println("Uk date format Date : " + df.format(date));
                
        dob=df.format(jDateChooser.getDate());
        
        pstmt.setString(1,formno);
        
        pstmt.setString(2,fst_name);
        pstmt.setString(3,lst_name);
        pstmt.setString(4,f_name);
        pstmt.setString(5,m_name);
        pstmt.setString(6,mobno);
        pstmt.setString(7,homephone);
        pstmt.setString(8,address);
        pstmt.setString(9,gender);
        pstmt.setString(10,marital_status);
        pstmt.setString(11,qualification);
        pstmt.setString(12,tenth);
        pstmt.setString(13,twelth);
        pstmt.setString(14,ug);
        pstmt.setString(15,pg);
        pstmt.setString(16,dob);    
     //   pstmt.setString(17,year);
         pstmt.setString(17,year);
        admit_date=(String)(df.format(date));
        pstmt.setString(18,admit_date);
        pstmt.setString(19,"-");
        
            pstmt2.setString(1,formno);
            rs=pstmt2.executeQuery(); 
            
            if(rs.next())
                 check_formno=rs.getString("FORM_NO");
                        
            if(formno.equalsIgnoreCase(check_formno)){
                JOptionPane.showMessageDialog(null,"Record already exists: Form Number = "+formno,"Record Duplication",JOptionPane.WARNING_MESSAGE);
            }
            else{                
                if((ImageIO.read(file)==null))
                    pstmt.clearParameters(); 
                else{    
                    int i= pstmt.executeUpdate();             
                        if(i==1){
                            fst_name+=" "+lst_name;
                            ImageProcessing.saveImage(fst_name,formno,"-");
                            JOptionPane.showMessageDialog(null,"Data uploaded successfully"); 
                            pstmt.clearParameters();
                            pstmt.close();
                        }
                        else
                            System.out.println("sorry data cannot be uploaded");
                    }
                }
                if(MainPage.option==1){                    
                    Register register=new Register();
                    register.setVisible(true);
                    this.setVisible(false);
                }
                else{
                      Admission ob=new Admission();
                    ob.setVisible(true);
                    this.setVisible(false);
                }
        }
        catch(SQLException e){
			System.out.println("Query Problem"+e);
		}
        catch(Exception em){
            JOptionPane.showMessageDialog(null,"PROBLEM IN UPLOADING DATA (Fill all details Carefully)    "+em);
        }
    submitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));    
    }//GEN-LAST:event_submitButtonActionPerformed

    private void firstnameTextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_firstnameTextFieldMouseExited
        if((firstnameTextField.getText()).trim().equals(""))
            firstnameTextField.setText("FIRST NAME");
    }//GEN-LAST:event_firstnameTextFieldMouseExited

    private void formNoTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formNoTextFieldKeyTyped
        char cr=evt.getKeyChar();        
        if(!(Character.isDigit(cr) || (cr==KeyEvent.VK_BACKSPACE)||cr==KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();            
        }         
    }//GEN-LAST:event_formNoTextFieldKeyTyped

/**
     * @param evt*
     * @param fieldname****************************************************************************************/
    public void checkNumbers(java.awt.event.KeyEvent evt,javax.swing.JTextField fieldname){
        char cr=evt.getKeyChar();
        if(!(Character.isDigit(cr) || (cr==KeyEvent.VK_BACKSPACE)||cr==KeyEvent.VK_DELETE)){
            getToolkit().beep();
            evt.consume();
        }
        if(fieldname.getText().length()>9){
            getToolkit().beep();
            evt.consume();                   
        }
    }
    private void mobile_numberTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobile_numberTextFieldKeyTyped
        checkNumbers(evt,mobile_numberTextField);        
    }//GEN-LAST:event_mobile_numberTextFieldKeyTyped

    private void homePhoneTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_homePhoneTextFieldKeyTyped
        checkNumbers(evt,homePhoneTextField);        
    }//GEN-LAST:event_homePhoneTextFieldKeyTyped

 /**
     * @param evt*
     * @param letters**************************************************************************************/
    public void checkLetters(java.awt.event.KeyEvent evt,String letters){
        char cr=evt.getKeyChar();
        if(!((Character.isLetter(cr))||(cr==KeyEvent.VK_BACKSPACE)||(cr==KeyEvent.VK_SPACE))){
            getToolkit().beep();
            evt.consume();
        }
        if(letters.length()>49){
                getToolkit().beep();
                evt.consume();                  
        }
    }   
    /**
     * @param fieldname*
     * @param fieldval*********************************************************************************/
    public void checkForBlank(javax.swing.JTextField fieldname,String fieldval){
      //  if((fieldname.getText().trim()).equalsIgnoreCase("")){
            fieldname.setText(fieldval);
            fieldname.requestFocusInWindow();
     //   }
    }
    
    private void firstnameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstnameTextFieldKeyTyped
        if((formNoTextField.getText().trim()).equalsIgnoreCase(""))
            checkForBlank(formNoTextField,"FORM NUMBER");
        else
            checkLetters(evt,firstnameTextField.getText());               
    }//GEN-LAST:event_firstnameTextFieldKeyTyped

    private void lastnameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastnameTextFieldKeyTyped
        checkLetters(evt,lastnameTextField.getText());
    }//GEN-LAST:event_lastnameTextFieldKeyTyped

    private void father_nameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_father_nameTextFieldKeyTyped
        checkLetters(evt,father_nameTextField.getText());
    }//GEN-LAST:event_father_nameTextFieldKeyTyped

    private void mother_nameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mother_nameTextFieldKeyTyped
        checkLetters(evt,mother_nameTextField.getText());
    }//GEN-LAST:event_mother_nameTextFieldKeyTyped

    /**
     * @param evt*
     * @param fieldname****************************************************************************************/
    public void checkForPercentage(java.awt.event.KeyEvent evt,javax.swing.JTextField fieldname){
        char cr=evt.getKeyChar();
        System.out.println(""+cr);
        if(!(Character.isDigit(cr)||((int)cr==46)||cr==KeyEvent.VK_BACKSPACE)){
            getToolkit().beep();
            evt.consume();
        }
        if(fieldname.getText().length()>4){
            getToolkit().beep();
            evt.consume();
        }
    }           
    
    private void tenthPerTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tenthPerTextFieldKeyTyped
        checkForPercentage(evt,tenthPerTextField);
    }//GEN-LAST:event_tenthPerTextFieldKeyTyped

    private void twelthPerTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_twelthPerTextFieldKeyTyped
        checkForPercentage(evt,twelthPerTextField);
    }//GEN-LAST:event_twelthPerTextFieldKeyTyped

    private void ugPerTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ugPerTextFieldKeyTyped
        checkForPercentage(evt,ugPerTextField);
    }//GEN-LAST:event_ugPerTextFieldKeyTyped

    private void pgPerTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pgPerTextFieldKeyTyped
        checkForPercentage(evt,pgPerTextField);
    }//GEN-LAST:event_pgPerTextFieldKeyTyped

    private void formNoTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formNoTextFieldKeyReleased
        String formno=formNoTextField.getText();        
        int i=MyCheck.checkAvailability(formno);
         if(i==1)
             msgLabel.setVisible(true);
         else
             msgLabel.setVisible(false);        
    }//GEN-LAST:event_formNoTextFieldKeyReleased

    private void formNoTextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formNoTextFieldMouseExited
        if((formNoTextField.getText()).trim().equals(""))
            formNoTextField.setText("FORM NUMBER");
    }//GEN-LAST:event_formNoTextFieldMouseExited

    private void formNoTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formNoTextFieldMouseClicked
        checkFor(formNoTextField,"FORM NUMBER");
    }//GEN-LAST:event_formNoTextFieldMouseClicked

    private void lastnameTextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lastnameTextFieldMouseExited
        if((lastnameTextField.getText()).trim().equals(""))
            lastnameTextField.setText("LAST NAME");
    }//GEN-LAST:event_lastnameTextFieldMouseExited

    private void father_nameTextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_father_nameTextFieldMouseExited
        if((father_nameTextField.getText()).trim().equals(""))
            father_nameTextField.setText("FATHER'S NAME");
    }//GEN-LAST:event_father_nameTextFieldMouseExited

    private void mother_nameTextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mother_nameTextFieldMouseExited
        if((mother_nameTextField.getText()).trim().equals(""))
            mother_nameTextField.setText("MOTHER'S NAME");
    }//GEN-LAST:event_mother_nameTextFieldMouseExited

    private void mobile_numberTextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mobile_numberTextFieldMouseExited
        if((mobile_numberTextField.getText()).trim().equals(""))
            mobile_numberTextField.setText("MOBILE NUMBER");
    }//GEN-LAST:event_mobile_numberTextFieldMouseExited

    private void homePhoneTextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePhoneTextFieldMouseExited
        if((homePhoneTextField.getText()).trim().equals(""))
            homePhoneTextField.setText("HOME PHONE");
    }//GEN-LAST:event_homePhoneTextFieldMouseExited

    private void addressTextAreaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addressTextAreaMouseExited
        if((addressTextArea.getText()).trim().equals(""))
            addressTextArea.setText("Correspondence Address");
    }//GEN-LAST:event_addressTextAreaMouseExited

    private void tenthPerTextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tenthPerTextFieldMouseExited
        if((tenthPerTextField.getText()).trim().equals(""))
            tenthPerTextField.setText("00.00");
    }//GEN-LAST:event_tenthPerTextFieldMouseExited

    private void twelthPerTextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_twelthPerTextFieldMouseExited
        if((twelthPerTextField.getText()).trim().equals(""))
            twelthPerTextField.setText("00.00");
    }//GEN-LAST:event_twelthPerTextFieldMouseExited

    private void ugPerTextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ugPerTextFieldMouseExited
        if((ugPerTextField.getText()).trim().equals(""))
            ugPerTextField.setText("00.00");
    }//GEN-LAST:event_ugPerTextFieldMouseExited

    private void pgPerTextFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pgPerTextFieldMouseExited
        if((pgPerTextField.getText()).trim().equals(""))
            pgPerTextField.setText("00.00");
    }//GEN-LAST:event_pgPerTextFieldMouseExited

    private void refreshLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshLabelMouseClicked
        Admission ob=new Admission();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_refreshLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admission.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admission().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addressTextArea;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField father_nameTextField;
    private javax.swing.JTextField firstnameTextField;
    private javax.swing.JTextField formNoTextField;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JTextField homePhoneTextField;
    private javax.swing.JLabel imgLabel;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastnameTextField;
    private javax.swing.JButton mainMenuButton;
    private javax.swing.JComboBox<String> maritalStatusComboBox;
    private javax.swing.JTextField mobile_numberTextField;
    private javax.swing.JTextField mother_nameTextField;
    private javax.swing.JLabel msgLabel;
    private javax.swing.JTextField pgPerTextField;
    private javax.swing.JComboBox<String> qualificationComboBox;
    private javax.swing.JLabel refreshLabel;
    private javax.swing.JButton submitButton;
    private javax.swing.JTextField tenthPerTextField;
    private javax.swing.JTextField twelthPerTextField;
    private javax.swing.JTextField ugPerTextField;
    private javax.swing.JLabel uploadLabel;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
