/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyProject1;

import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.util.Date;
import java.util.Locale;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author SANTOSH
 */
public class BirthDay extends javax.swing.JFrame {

   //     Connection con;
        ResultSet rs=null;
        PreparedStatement pstmt; 
        String dob="";        
    
    /**
     * Creates new form BirthDay1
     */
    public BirthDay() {
        initComponents();
        this.setLocationRelativeTo(null);
        myBirthDay();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        wishjLabel = new javax.swing.JLabel();
        showImagejLabel = new javax.swing.JLabel();
        namejLabel = new javax.swing.JLabel();
        dobjLabel = new javax.swing.JLabel();
        previousjButton = new javax.swing.JButton();
        nextjButton = new javax.swing.JButton();
        yearLabel = new javax.swing.JLabel();
        mainmenuButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        noLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        wishjLabel.setBackground(new java.awt.Color(153, 153, 255));
        wishjLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        wishjLabel.setForeground(new java.awt.Color(255, 255, 255));
        wishjLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wishjLabel.setText("NO ONE HAS BIRTH DAY TODAY");

        showImagejLabel.setBackground(new java.awt.Color(255, 204, 204));
        showImagejLabel.setText("        Students image");
        showImagejLabel.setOpaque(true);

        namejLabel.setBackground(new java.awt.Color(255, 204, 204));
        namejLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        namejLabel.setForeground(new java.awt.Color(255, 255, 255));
        namejLabel.setText("SANTOSH KUMAR SAHU");

        dobjLabel.setBackground(new java.awt.Color(255, 204, 204));
        dobjLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        dobjLabel.setForeground(new java.awt.Color(255, 255, 255));
        dobjLabel.setText("09-mar-1996");

        previousjButton.setBackground(new java.awt.Color(0, 51, 204));
        previousjButton.setForeground(new java.awt.Color(255, 255, 255));
        previousjButton.setText("Previous");
        previousjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousjButtonActionPerformed(evt);
            }
        });

        nextjButton.setBackground(new java.awt.Color(0, 51, 204));
        nextjButton.setForeground(new java.awt.Color(255, 255, 255));
        nextjButton.setText("Next");
        nextjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextjButtonActionPerformed(evt);
            }
        });

        yearLabel.setBackground(new java.awt.Color(255, 204, 204));
        yearLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        yearLabel.setForeground(new java.awt.Color(255, 255, 255));
        yearLabel.setText("2011");

        mainmenuButton.setBackground(new java.awt.Color(0, 51, 204));
        mainmenuButton.setForeground(new java.awt.Color(255, 255, 255));
        mainmenuButton.setText("<< Main Menu");
        mainmenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainmenuButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NAME :");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DATE OF BIRTH :");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ACADEMIC YEAR :");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("SECTION : ");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("A");

        noLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        noLabel.setForeground(new java.awt.Color(255, 255, 255));
        noLabel.setText("100");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(previousjButton)
                .addGap(129, 129, 129)
                .addComponent(nextjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainmenuButton)
                .addGap(155, 155, 155))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wishjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(noLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dobjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(namejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(showImagejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(142, 142, 142))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(wishjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(noLabel)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dobjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(yearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(showImagejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(184, 184, 184)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainmenuButton)
                    .addComponent(nextjButton)
                    .addComponent(previousjButton))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @return *************************************************************************/
    public int checkBirthDay(){
        int count=0;
        try{
                  pstmt=MyLogin.con.prepareStatement("select S_ID,FIRST_NAME,LAST_NAME,DOB,A_YEAR from Admission_Table where DOB like ? and S_ID != '-'",ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            
            Date date = new Date();
		DateFormat df;
		df = DateFormat.getDateInstance(DateFormat.MEDIUM, Locale.UK);
		System.out.println("Uk date format Date : " + df.format(date));
                
            dob=(String)(df.format(date));     
            dob=(dob.substring(0, 6));
           
           System.out.println(""+dob);
       //    pstmt.setString(1,"\'%"+dob+"%\'");    // not working with this command
            pstmt.setString(1,"%"+dob+"%");
   //         pstmt.setString(2, "2017");
            rs=pstmt.executeQuery();  
            pstmt.clearParameters(); 
            for(count=0;rs.next();count++);
        }catch(Exception e){
            System.out.println("problem inside checkBirthDay "+e);
        }
        return count;
    }
    
    /**************************************************************************/
    private void myBirthDay(){                                    
        try{
         /*   MyConnection Ob=new MyConnection();               
            con = Ob.connectMe();
            System.out.println("Santosh connection"); */
    //        Statement st=con.createStatement();
      //      pstmt=con.prepareStatement("select * from Teacher_Detail where T_DOB like ?");
                            //or
      /*      pstmt=MyLogin.con.prepareStatement("select S_ID,FIRST_NAME,LAST_NAME,DOB,A_YEAR from Admission_Table where DOB like ? and S_ID != '-'",ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            
            Date date = new Date();
		DateFormat df;
		df = DateFormat.getDateInstance(DateFormat.MEDIUM, Locale.UK);
		System.out.println("Uk date format Date : " + df.format(date));
                
            dob=(String)(df.format(date));     
            dob=(dob.substring(0, 6));
           
           System.out.println(""+dob);
       //    pstmt.setString(1,"\'%"+dob+"%\'");    // not working with this command
            pstmt.setString(1,"%"+dob+"%");
   //         pstmt.setString(2, "2017");
            rs=pstmt.executeQuery();  
            pstmt.clearParameters();  */
      int i=checkBirthDay();
      if(i>0){
          rs.first();
          setData();
      }
    //   nextjButtonActionPerformed(null);       
         //   setData();
        }
        catch(Exception e){
            System.out.println(" problem inside myBirthDay Method"+e);
        }
    }    
    /************************************************************************************/    
    public void setData(){
        try{                                 
                    BufferedImage originalImg=ImageIO.read(new File(".\\test\\Record\\Student_Images\\Registered\\"+rs.getString("FIRST_NAME")+" "+rs.getString("LAST_NAME")+""+rs.getString("S_ID")+".jpg"));    // to read image do this
                ImageIcon icon=new ImageIcon(ImageProcessing.myResize(originalImg,showImagejLabel.getWidth(),showImagejLabel.getHeight()));
                    showImagejLabel.setIcon(icon);
                    
                    wishjLabel.setText("WISH YOU HAPPY BIRTHDAY DEAR : "+rs.getString("FIRST_NAME")+" "+rs.getString("LAST_NAME"));                                                                                           
                    namejLabel.setText(""+rs.getString("FIRST_NAME")+" "+rs.getString("LAST_NAME"));
                    dobjLabel.setText(rs.getString("DOB"));                                              
                    yearLabel.setText(""+rs.getString("A_YEAR"));
             //       MySpeak.mySpeach("WISH YOU HAPPY BIRTHDAY DEAR : "+rs.getString("FIRST_NAME")+" "+rs.getString("LAST_NAME")+",May God bless you !!!");
        }
         catch(Exception e){            
        }  
    }    
    
    private void previousjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousjButtonActionPerformed
        previousjButton.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        try{
            if(rs.previous())	// pre-defined method
                setData();
            else
                rs.next();
        }
        catch (Exception ex){
        }
        previousjButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_previousjButtonActionPerformed

    private void nextjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextjButtonActionPerformed
        nextjButton.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        try{
            if(rs.next())	// pre-defined method
                setData();
            else
                rs.previous();
        }
        catch (Exception ex){
        }
        nextjButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_nextjButtonActionPerformed

    private void mainmenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainmenuButtonActionPerformed
        mainmenuButton.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        MainPage ob=new MainPage();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mainmenuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BirthDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BirthDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BirthDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BirthDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BirthDay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dobjLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mainmenuButton;
    private javax.swing.JLabel namejLabel;
    private javax.swing.JButton nextjButton;
    private javax.swing.JLabel noLabel;
    private javax.swing.JButton previousjButton;
    private javax.swing.JLabel showImagejLabel;
    private javax.swing.JLabel wishjLabel;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
