/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyProject1;

import static MyProject1.MyLogin.con;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SANTOSH
 */
public class FeeDetail extends javax.swing.JFrame {
        
        PreparedStatement pstmt;
        ResultSet rs_tab1,rs_tab2;
    
    /**
     * Creates new form FeeDetail
     */
    public FeeDetail() {        
        pstmt=null;
        rs_tab1=null;
        rs_tab2=null;
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
    //    DateChooser.setVisible(false);
    //    YearChooser.setVisible(false);
    //    ok1Button.setVisible(false);
    //    ok2Button.setVisible(false);
        
        this.setLocationRelativeTo(null);         
        Calendar calendar = Calendar.getInstance();
     
        YearChooser.setEndYear(calendar.get(Calendar.YEAR)); //will set current year as end year
        YearChooser.setValue(calendar.get(Calendar.YEAR));  //will set only value to be visibled
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        YearChooser = new com.toedter.calendar.JYearChooser();
        ok1Button = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        DateChooser = new com.toedter.calendar.JDateChooser();
        ok2Button = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        amountTextField = new javax.swing.JTextField();
        ok3Button = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        paidLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        unpaidLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        totLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        refreshLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        msgLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));

        Table.setBackground(new java.awt.Color(0, 0, 102));
        Table.setForeground(new java.awt.Color(255, 255, 255));
        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NAME", "FATHER'S NAME", "PAY1", "DATE1", "PAY2", "DATE2", "PAY3", "DATE3"
            }
        ));
        Table.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(Table);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Choose Year to See Detail :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        YearChooser.setBackground(new java.awt.Color(0, 0, 102));
        YearChooser.setStartYear(2017);
        jPanel1.add(YearChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 41, 118, 51));

        ok1Button.setBackground(new java.awt.Color(0, 51, 204));
        ok1Button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ok1Button.setForeground(new java.awt.Color(255, 255, 255));
        ok1Button.setText("OK");
        ok1Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ok1ButtonMouseClicked(evt);
            }
        });
        jPanel1.add(ok1Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 55, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Choose Date to See Detail :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        DateChooser.setBackground(new java.awt.Color(0, 0, 102));
        DateChooser.setForeground(new java.awt.Color(255, 255, 255));
        DateChooser.setDateFormatString(" d MMM, yyyy");
        DateChooser.setFont(new java.awt.Font("Arial Narrow", 1, 13)); // NOI18N
        DateChooser.setMaxSelectableDate(new java.util.Date(253370748660000L));
        jPanel2.add(DateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 41, 115, 52));

        ok2Button.setBackground(new java.awt.Color(0, 51, 204));
        ok2Button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ok2Button.setForeground(new java.awt.Color(255, 255, 255));
        ok2Button.setText("OK");
        ok2Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ok2ButtonMouseClicked(evt);
            }
        });
        jPanel2.add(ok2Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 56, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));
        jPanel3.setForeground(new java.awt.Color(0, 0, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter Total Amount  :");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        amountTextField.setFont(new java.awt.Font("Arial Narrow", 1, 13)); // NOI18N
        jPanel3.add(amountTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 47, 126, -1));

        ok3Button.setBackground(new java.awt.Color(0, 51, 204));
        ok3Button.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        ok3Button.setForeground(new java.awt.Color(255, 255, 255));
        ok3Button.setText("OK");
        ok3Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ok3ButtonMouseClicked(evt);
            }
        });
        jPanel3.add(ok3Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 46, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Students ");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 89, -1, -1));

        paidLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        paidLabel.setForeground(new java.awt.Color(255, 255, 255));
        paidLabel.setText("0");
        jPanel3.add(paidLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 144, 49, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Completed :");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 144, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Incomplete :");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 177, -1, -1));

        unpaidLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        unpaidLabel.setForeground(new java.awt.Color(255, 255, 255));
        unpaidLabel.setText("0");
        jPanel3.add(unpaidLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 177, 49, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Total :");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 111, -1, -1));

        totLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        totLabel.setForeground(new java.awt.Color(255, 255, 255));
        totLabel.setText("0");
        jPanel3.add(totLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 111, 49, -1));

        jPanel4.setBackground(new java.awt.Color(0, 51, 153));

        backButton.setBackground(new java.awt.Color(0, 51, 204));
        backButton.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("<<Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(backButton)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 51, 153));

        jLabel5.setBackground(new java.awt.Color(255, 0, 0));
        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("FEE DETAIL");

        refreshLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        refreshLabel.setForeground(new java.awt.Color(255, 255, 255));
        refreshLabel.setText("Refresh");
        refreshLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refreshLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(493, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(365, 365, 365)
                .addComponent(refreshLabel)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(refreshLabel)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 0, 102));

        msgLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        msgLabel.setForeground(new java.awt.Color(255, 255, 255));
        msgLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(343, 343, 343)
                .addComponent(msgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(357, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(msgLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2))
                        .addGap(12, 12, 12))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ok1ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ok1ButtonMouseClicked
        // TODO add your handling code here:
        rs_tab1=null;
        rs_tab2=null;
        String yr=""+YearChooser.getYear();
        msgLabel.setText("LIST OF THE STUDENTS : "+yr);
        try{
            pstmt=con.prepareStatement("select S_ID,FIRST_NAME,LAST_NAME,FATHER_NAME from ADMISSION_TABLE where S_ID like ? order by S_ID",ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
            pstmt.setString(1,"%"+yr+"%");
       //     pstmt.setString(2, "-");
            rs_tab1=pstmt.executeQuery();
            pstmt.clearParameters();
            
            pstmt=con.prepareStatement("select * from FEE_DETAIL_TABLE where S_ID like ? order by S_ID",ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
            pstmt.setString(1,"%"+yr+"%");
            rs_tab2=pstmt.executeQuery();
            pstmt.clearParameters();
           
            DefaultTableModel tm=(DefaultTableModel)Table.getModel();        
            while(true)
                {
                    int c=tm.getRowCount();
                    if(c==0)
                        break;
                    else
                         tm.removeRow(0);
                }
            while(rs_tab2.next()){
                if(rs_tab1.next()){
                        Object kk[]={rs_tab2.getString("S_ID"),rs_tab1.getString("FIRST_NAME")+" "+rs_tab1.getString("LAST_NAME"),rs_tab1.getString("FATHER_NAME"),rs_tab2.getString("PAY1"),rs_tab2.getString("DATE1"),rs_tab2.getString("PAY2"),rs_tab2.getString("DATE2"),rs_tab2.getString("PAY3"),rs_tab2.getString("DATE3")};
                        tm.addRow(kk);
                    } 
            }
        }catch(Exception e){
            System.out.println("Problem inside ok1Button"+e);
        }        
    }//GEN-LAST:event_ok1ButtonMouseClicked

    private void ok2ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ok2ButtonMouseClicked
        // TODO add your handling code here:        
        rs_tab1=null;
        rs_tab2=null;
        String dt="";
        try{
            Date date = new Date();
		DateFormat df;
		df = DateFormat.getDateInstance(DateFormat.MEDIUM, Locale.UK);
		System.out.println("Uk date format Date : " + df.format(date));
                
            dt=df.format(DateChooser.getDate());
            msgLabel.setText("LIST OF THE STUDENTS PAID ON :"+dt);
            
            pstmt=con.prepareStatement("select * from FEE_DETAIL_TABLE where DATE1 = ? or DATE2 = ? or DATE3 = ? order by S_ID",ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);            
            pstmt.setString(1, dt);
            pstmt.setString(2, dt);
            pstmt.setString(3, dt);        
            rs_tab2=pstmt.executeQuery();
            pstmt.clearParameters();

            DefaultTableModel tm=(DefaultTableModel)Table.getModel();        
            while(true)
                {
                    int c=tm.getRowCount();
                    if(c==0)
                        break;
                    else
                         tm.removeRow(0);
                }
            while(rs_tab2.next()){
                    pstmt=con.prepareStatement("select S_ID,FIRST_NAME,LAST_NAME,FATHER_NAME from ADMISSION_TABLE where S_ID = ?",ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
                    pstmt.setString(1, rs_tab2.getString("S_ID"));
                    rs_tab1=pstmt.executeQuery();
                    if(rs_tab1.next()){
                        Object kk[]={rs_tab2.getString("S_ID"),rs_tab1.getString("FIRST_NAME")+" "+rs_tab1.getString("LAST_NAME"),rs_tab1.getString("FATHER_NAME"),rs_tab2.getString("PAY1"),rs_tab2.getString("DATE1"),rs_tab2.getString("PAY2"),rs_tab2.getString("DATE2"),rs_tab2.getString("PAY3"),rs_tab2.getString("DATE3")};
                        tm.addRow(kk);
                    }                    
            }
        
        }catch(Exception e){
            System.out.println("Problem inside ok2Button"+e);
        }        
    }//GEN-LAST:event_ok2ButtonMouseClicked

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        MainPage ob=new MainPage();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backButtonActionPerformed

    private void ok3ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ok3ButtonMouseClicked
        // TODO add your handling code here:
        msgLabel.setText("LIST OF THE STUDENTS TO BE PAID");
        try{
            rs_tab1=null;
            rs_tab2=null;
            int p1=0,p2=0,p3=0;
            String yr=""+YearChooser.getYear();
            int amt=Integer.parseInt(amountTextField.getText().trim());
            
            pstmt=con.prepareStatement("select * from FEE_DETAIL_TABLE where S_ID like ? order by S_ID",ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
            pstmt.setString(1,"%"+yr+"%");
            rs_tab2=pstmt.executeQuery();
            pstmt.clearParameters();
            
            DefaultTableModel tm=(DefaultTableModel)Table.getModel();        
            while(true)
                {
                    int c=tm.getRowCount();
                    if(c==0)
                        break;
                    else
                         tm.removeRow(0);
                }            
            int tot=0,paid=0,unpaid=0;
            while(rs_tab2.next()){
                tot++;
                p1=p2=p3=0;
                p1=Integer.parseInt(rs_tab2.getString("PAY1"));
                p2=Integer.parseInt(rs_tab2.getString("PAY2"));
                p3=Integer.parseInt(rs_tab2.getString("PAY3"));
                if((p1+p2+p3)<amt){
                    unpaid++;
                    pstmt=con.prepareStatement("select S_ID,FIRST_NAME,LAST_NAME,FATHER_NAME from ADMISSION_TABLE where S_ID = ?",ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_READ_ONLY);
                    pstmt.setString(1, rs_tab2.getString("S_ID"));
                    rs_tab1=pstmt.executeQuery();
                    if(rs_tab1.next()){
                        Object kk[]={rs_tab2.getString("S_ID"),rs_tab1.getString("FIRST_NAME")+" "+rs_tab1.getString("LAST_NAME"),rs_tab1.getString("FATHER_NAME"),rs_tab2.getString("PAY1"),rs_tab2.getString("DATE1"),rs_tab2.getString("PAY2"),rs_tab2.getString("DATE2"),rs_tab2.getString("PAY3"),rs_tab2.getString("DATE3")};
                        tm.addRow(kk);
                    } 
                }
            }
            paid=tot-unpaid;
            totLabel.setText(""+tot);
            paidLabel.setText(""+paid);
            unpaidLabel.setText(""+unpaid);
            
        }catch(Exception e){
            System.out.println("Problem inside ok3Button "+e);
        }
        
    }//GEN-LAST:event_ok3ButtonMouseClicked

    private void refreshLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshLabelMouseClicked
        FeeDetail ob=new FeeDetail();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_refreshLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FeeDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FeeDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FeeDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FeeDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FeeDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateChooser;
    private javax.swing.JTable Table;
    private com.toedter.calendar.JYearChooser YearChooser;
    private javax.swing.JTextField amountTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel msgLabel;
    private javax.swing.JButton ok1Button;
    private javax.swing.JButton ok2Button;
    private javax.swing.JButton ok3Button;
    private javax.swing.JLabel paidLabel;
    private javax.swing.JLabel refreshLabel;
    private javax.swing.JLabel totLabel;
    private javax.swing.JLabel unpaidLabel;
    // End of variables declaration//GEN-END:variables
}
