/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyProject1;

import java.text.DateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import javax.swing.JFrame;

/**
 *
 * @author SANTOSH
 */
public class MainPage extends javax.swing.JFrame {
      
      public static int option;

    /**
     * Creates new form MainPage
     */
    public MainPage() {
     //   option=0;
     //   AdminControl.year=0;      
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        this.setLocationRelativeTo(null);
        
        Calendar calendar = Calendar.getInstance();     
        jYearChooser1.setEndYear(calendar.get(Calendar.YEAR)); //will set current year as end year
        jYearChooser1.setValue(calendar.get(Calendar.YEAR));  //will set only value to be visibled
        
        this.setTitle(" A man who thinks about future can never lose any moment of life -SANTOSH SAHU");
        if(MyLogin.voiceFlag==1){
            MySpeak.mySpeach("welcome to oxford spoken english academy");         
            MyLogin.voiceFlag=2;                    
        }            
        
        BirthDay ob=new BirthDay();
        int i=ob.checkBirthDay();
        if(i>0){
            birthdayLabel.setEnabled(true);
            birthdayLabel.setText(i+" Birthday(s) Today");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        admissionButton = new javax.swing.JButton();
        totalAddButton = new javax.swing.JButton();
        jInternalFrame2 = new javax.swing.JInternalFrame();
        new_registerButton = new javax.swing.JButton();
        totalRegdButton = new javax.swing.JButton();
        jInternalFrame3 = new javax.swing.JInternalFrame();
        j2011Button = new javax.swing.JButton();
        j2012Button = new javax.swing.JButton();
        j2013Button = new javax.swing.JButton();
        j2014Button = new javax.swing.JButton();
        j2015Button = new javax.swing.JButton();
        j2016Button = new javax.swing.JButton();
        j2017Button = new javax.swing.JButton();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        jLabel2 = new javax.swing.JLabel();
        OKButton = new javax.swing.JButton();
        jInternalFrame5 = new javax.swing.JInternalFrame();
        payFeeButton = new javax.swing.JButton();
        feeDetailButton = new javax.swing.JButton();
        jInternalFrame6 = new javax.swing.JInternalFrame();
        staffButton = new javax.swing.JButton();
        jInternalFrame7 = new javax.swing.JInternalFrame();
        insertButton = new javax.swing.JButton();
        modifyButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        viewButton = new javax.swing.JButton();
        jInternalFrame4 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        contentTextArea = new javax.swing.JTextArea();
        speakButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        refreshLabel = new javax.swing.JLabel();
        logoutLabel = new javax.swing.JLabel();
        birthdayLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jInternalFrame1.setBackground(new java.awt.Color(255, 255, 255));
        jInternalFrame1.setVisible(true);

        admissionButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyProject1/icons/NEW_ADMISSION.png"))); // NOI18N
        admissionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admissionButtonActionPerformed(evt);
            }
        });

        totalAddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyProject1/icons/TOTAL.png"))); // NOI18N
        totalAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalAddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(admissionButton)
                .addGap(81, 81, 81)
                .addComponent(totalAddButton)
                .addContainerGap(833, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalAddButton)
                    .addComponent(admissionButton))
                .addGap(249, 249, 249))
        );

        jTabbedPane2.addTab("            ADMISSION          ", jInternalFrame1);

        jInternalFrame2.setVisible(true);

        new_registerButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyProject1/icons/NEW_REGISTER.png"))); // NOI18N
        new_registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_registerButtonActionPerformed(evt);
            }
        });

        totalRegdButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyProject1/icons/TOTAL.png"))); // NOI18N
        totalRegdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalRegdButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame2Layout = new javax.swing.GroupLayout(jInternalFrame2.getContentPane());
        jInternalFrame2.getContentPane().setLayout(jInternalFrame2Layout);
        jInternalFrame2Layout.setHorizontalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(new_registerButton)
                .addGap(82, 82, 82)
                .addComponent(totalRegdButton)
                .addContainerGap(831, Short.MAX_VALUE))
        );
        jInternalFrame2Layout.setVerticalGroup(
            jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame2Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(jInternalFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalRegdButton)
                    .addComponent(new_registerButton))
                .addContainerGap(248, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("           REGISTER           ", jInternalFrame2);

        jInternalFrame3.setVisible(true);

        j2011Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyProject1/icons/2011.png"))); // NOI18N
        j2011Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2011ButtonActionPerformed(evt);
            }
        });

        j2012Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyProject1/icons/2012.png"))); // NOI18N
        j2012Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2012ButtonActionPerformed(evt);
            }
        });

        j2013Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyProject1/icons/2013.png"))); // NOI18N
        j2013Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2013ButtonActionPerformed(evt);
            }
        });

        j2014Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyProject1/icons/2014.png"))); // NOI18N
        j2014Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2014ButtonActionPerformed(evt);
            }
        });

        j2015Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyProject1/icons/2015.png"))); // NOI18N
        j2015Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2015ButtonActionPerformed(evt);
            }
        });

        j2016Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyProject1/icons/2016.png"))); // NOI18N
        j2016Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2016ButtonActionPerformed(evt);
            }
        });

        j2017Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyProject1/icons/2017.png"))); // NOI18N
        j2017Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j2017ButtonActionPerformed(evt);
            }
        });

        jYearChooser1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jYearChooser1.setStartYear(2011);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("OR");

        OKButton.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        OKButton.setText("OK");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame3Layout = new javax.swing.GroupLayout(jInternalFrame3.getContentPane());
        jInternalFrame3.getContentPane().setLayout(jInternalFrame3Layout);
        jInternalFrame3Layout.setHorizontalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addGap(1046, 1046, 1046)
                        .addComponent(j2015Button))
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                                .addComponent(j2011Button)
                                .addGap(82, 82, 82)
                                .addComponent(j2012Button))
                            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                                .addComponent(j2016Button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(j2017Button)))
                        .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(j2013Button)
                                .addGap(74, 74, 74))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116)))
                        .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jYearChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(j2014Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addComponent(OKButton)))
                .addGap(103, 122, Short.MAX_VALUE))
        );
        jInternalFrame3Layout.setVerticalGroup(
            jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(j2011Button))
                            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                                .addGap(294, 294, 294)
                                .addComponent(j2016Button)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                                .addComponent(j2012Button)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(j2017Button))
                            .addGroup(jInternalFrame3Layout.createSequentialGroup()
                                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(j2014Button)
                                    .addComponent(j2013Button)
                                    .addComponent(j2015Button))
                                .addGroup(jInternalFrame3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                                        .addGap(111, 111, 111)
                                        .addComponent(OKButton)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jInternalFrame3Layout.createSequentialGroup()
                                        .addGap(57, 57, 57)
                                        .addComponent(jYearChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)))))))
                .addGap(89, 89, 89))
        );

        jTabbedPane2.addTab("          STUDENT LIST         ", jInternalFrame3);

        jInternalFrame5.setVisible(true);

        payFeeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyProject1/icons/PAY_FEE.png"))); // NOI18N
        payFeeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        payFeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payFeeButtonActionPerformed(evt);
            }
        });

        feeDetailButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyProject1/icons/FEE_DETAIL.png"))); // NOI18N
        feeDetailButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        feeDetailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feeDetailButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame5Layout = new javax.swing.GroupLayout(jInternalFrame5.getContentPane());
        jInternalFrame5.getContentPane().setLayout(jInternalFrame5Layout);
        jInternalFrame5Layout.setHorizontalGroup(
            jInternalFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame5Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(payFeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(feeDetailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(831, Short.MAX_VALUE))
        );
        jInternalFrame5Layout.setVerticalGroup(
            jInternalFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame5Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jInternalFrame5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(feeDetailButton)
                    .addComponent(payFeeButton))
                .addContainerGap(251, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("                   FEE                   ", jInternalFrame5);

        jInternalFrame6.setVisible(true);

        staffButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyProject1/icons/STAFF_DETAIL.png"))); // NOI18N
        staffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame6Layout = new javax.swing.GroupLayout(jInternalFrame6.getContentPane());
        jInternalFrame6.getContentPane().setLayout(jInternalFrame6Layout);
        jInternalFrame6Layout.setHorizontalGroup(
            jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame6Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(staffButton)
                .addContainerGap(1075, Short.MAX_VALUE))
        );
        jInternalFrame6Layout.setVerticalGroup(
            jInternalFrame6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame6Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(staffButton)
                .addContainerGap(251, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("          STAFF DETAIL          ", jInternalFrame6);

        jInternalFrame7.setVisible(true);

        insertButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyProject1/icons/INSERT.png"))); // NOI18N
        insertButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });

        modifyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyProject1/icons/MODIFY.png"))); // NOI18N
        modifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyButtonActionPerformed(evt);
            }
        });

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyProject1/icons/DELETE.png"))); // NOI18N
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        viewButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyProject1/icons/VIEW.png"))); // NOI18N
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame7Layout = new javax.swing.GroupLayout(jInternalFrame7.getContentPane());
        jInternalFrame7.getContentPane().setLayout(jInternalFrame7Layout);
        jInternalFrame7Layout.setHorizontalGroup(
            jInternalFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame7Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(insertButton)
                .addGap(78, 78, 78)
                .addComponent(modifyButton)
                .addGap(79, 79, 79)
                .addComponent(deleteButton)
                .addGap(83, 83, 83)
                .addComponent(viewButton)
                .addContainerGap(351, Short.MAX_VALUE))
        );
        jInternalFrame7Layout.setVerticalGroup(
            jInternalFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame7Layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addGroup(jInternalFrame7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewButton)
                    .addComponent(deleteButton)
                    .addComponent(modifyButton)
                    .addComponent(insertButton))
                .addContainerGap(249, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("          ADMIN CONTROL         ", jInternalFrame7);

        jInternalFrame4.setVisible(true);

        contentTextArea.setColumns(20);
        contentTextArea.setRows(5);
        jScrollPane1.setViewportView(contentTextArea);

        speakButton.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        speakButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyProject1/icons/Pronounce.png"))); // NOI18N
        speakButton.setText("Pronounce");
        speakButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speakButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame4Layout = new javax.swing.GroupLayout(jInternalFrame4.getContentPane());
        jInternalFrame4.getContentPane().setLayout(jInternalFrame4Layout);
        jInternalFrame4Layout.setHorizontalGroup(
            jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 802, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(speakButton)
                .addContainerGap(305, Short.MAX_VALUE))
        );
        jInternalFrame4Layout.setVerticalGroup(
            jInternalFrame4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jInternalFrame4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(speakButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("                    TOOLS                    ", jInternalFrame4);

        jPanel1.setBackground(new java.awt.Color(0, 0, 153));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setBackground(new java.awt.Color(204, 204, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("OXFORD SPOKEN ENGLISH ACADEMY");

        jLabel3.setBackground(new java.awt.Color(255, 255, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("INDIRA NAGAR SARSIWA, DIST - BALODABAZAR-BHATAPARA (C.G.) 493559");

        refreshLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        refreshLabel.setForeground(new java.awt.Color(255, 255, 255));
        refreshLabel.setText("Refresh");
        refreshLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        refreshLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                refreshLabelMouseClicked(evt);
            }
        });

        logoutLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        logoutLabel.setForeground(new java.awt.Color(255, 255, 255));
        logoutLabel.setText("Log Out");
        logoutLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutLabelMouseClicked(evt);
            }
        });

        birthdayLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        birthdayLabel.setForeground(new java.awt.Color(255, 204, 0));
        birthdayLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        birthdayLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        birthdayLabel.setEnabled(false);
        birthdayLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                birthdayLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(birthdayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(149, 149, 149)
                        .addComponent(logoutLabel)
                        .addGap(18, 18, 18)
                        .addComponent(refreshLabel)
                        .addGap(48, 48, 48)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(refreshLabel)
                        .addComponent(logoutLabel))
                    .addComponent(birthdayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane2))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 558, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void admissionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admissionButtonActionPerformed
        // TODO add your handling code here:
        admissionButton.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        Date date = new Date();
		DateFormat df;
		df = DateFormat.getDateInstance(DateFormat.MEDIUM, Locale.UK);
		System.out.println("Uk date format Date : " + df.format(date));
           String  regd_date=(String)(df.format(date));
     //   AdminControl.year=2017;
            regd_date=regd_date.substring(7,11);
           AdminControl.year=Integer.parseInt(regd_date);
           
            option=0;
        Admission admission=new Admission();
        admission.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_admissionButtonActionPerformed

    private void totalAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalAddButtonActionPerformed
        // TODO add your handling code here:
        AdmissionDetail ob=new AdmissionDetail();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_totalAddButtonActionPerformed

    /************************************************************************************/
    private void admin_showingSection(){
        Section ob=new Section();
        ob.setVisible(true);
        this.setVisible(false);   
    }
    
    private void j2011ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2011ButtonActionPerformed
        // TODO add your handling code here:
        j2011Button.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        option=4;
        AdminControl.year=2011;
        admin_showingSection();
    }//GEN-LAST:event_j2011ButtonActionPerformed

    private void payFeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payFeeButtonActionPerformed
        // TODO add your handling code here:
        payFeeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        PayFee payfee=new PayFee();
        payfee.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_payFeeButtonActionPerformed

    private void feeDetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feeDetailButtonActionPerformed
        // TODO add your handling code here:
        FeeDetail ob=new FeeDetail();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_feeDetailButtonActionPerformed
//********************************************
    private void password(){
        Password pass=new Password();
        pass.setVisible(true);
        this.setVisible(false);
    }
    
    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
        // TODO add your handling code here:
        insertButton.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        option=1;
        password();
    }//GEN-LAST:event_insertButtonActionPerformed

    private void modifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyButtonActionPerformed
        // TODO add your handling code here:
        modifyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        option=2;
        password();
    }//GEN-LAST:event_modifyButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        deleteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        option=3;
        password();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        // TODO add your handling code here:
        viewButton.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        option=4;
        password();
    }//GEN-LAST:event_viewButtonActionPerformed

    private void j2015ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2015ButtonActionPerformed
        // TODO add your handling code here:
        j2015Button.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        option=4;
        AdminControl.year=2015;
        admin_showingSection();
    }//GEN-LAST:event_j2015ButtonActionPerformed

    private void j2016ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2016ButtonActionPerformed
        // TODO add your handling code here:
        j2016Button.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        option=4;
        AdminControl.year=2016;
        admin_showingSection();
    }//GEN-LAST:event_j2016ButtonActionPerformed

    private void j2017ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2017ButtonActionPerformed
        // TODO add your handling code here:
        j2017Button.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        option=4;
        AdminControl.year=2017;
        admin_showingSection();
    }//GEN-LAST:event_j2017ButtonActionPerformed

    private void j2012ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2012ButtonActionPerformed
        // TODO add your handling code here:
        j2012Button.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        option=4;
        AdminControl.year=2012;
        admin_showingSection();        
    }//GEN-LAST:event_j2012ButtonActionPerformed

    private void j2013ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2013ButtonActionPerformed
        // TODO add your handling code here:
        j2013Button.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        option=4;
        AdminControl.year=2013;
        admin_showingSection();
    }//GEN-LAST:event_j2013ButtonActionPerformed

    private void j2014ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j2014ButtonActionPerformed
        // TODO add your handling code here:
        j2014Button.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        option=4;
        AdminControl.year=2014;
        admin_showingSection();
    }//GEN-LAST:event_j2014ButtonActionPerformed

    private void new_registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_registerButtonActionPerformed
        // TODO add your handling code here:
        new_registerButton.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        Date date = new Date();
		DateFormat df;
		df = DateFormat.getDateInstance(DateFormat.MEDIUM, Locale.UK);
		System.out.println("Uk date format Date : " + df.format(date));
           String  regd_date=(String)(df.format(date));
            regd_date=regd_date.substring(7,11);
            
           AdminControl.year=Integer.parseInt(regd_date); 
            option=0;
     //       AdminControl.year=2017;
            Register register= new Register();
            register.setVisible(true);
            this.setVisible(false);
            
    }//GEN-LAST:event_new_registerButtonActionPerformed

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        // TODO add your handling code here:
        OKButton.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        option=4;
         AdminControl.year=jYearChooser1.getYear();
    //    System.out.println(""+Admission.year);       
        admin_showingSection();
    }//GEN-LAST:event_OKButtonActionPerformed

    private void totalRegdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalRegdButtonActionPerformed
        // TODO add your handling code here:
        totalRegdButton.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        RegisteredDetail ob=new RegisteredDetail();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_totalRegdButtonActionPerformed

    private void staffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffButtonActionPerformed
        StaffDetail ob=new StaffDetail();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_staffButtonActionPerformed

    private void logoutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutLabelMouseClicked
        logoutLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        try{
            MyLogin.con.close();
        }catch(Exception e){ }
        
        MyLogin ob=new MyLogin();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutLabelMouseClicked

    private void refreshLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_refreshLabelMouseClicked
       refreshLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        MainPage ob=new MainPage();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_refreshLabelMouseClicked

    private void birthdayLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_birthdayLabelMouseClicked
        birthdayLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        BirthDay ob=new BirthDay();
        ob.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_birthdayLabelMouseClicked

    private void speakButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speakButtonActionPerformed
        speakButton.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        String content=contentTextArea.getText().trim();
        if(!(content.equalsIgnoreCase("")))
            MySpeak.mySpeach(content);
        speakButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_speakButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton OKButton;
    private javax.swing.JButton admissionButton;
    private javax.swing.JLabel birthdayLabel;
    private javax.swing.JTextArea contentTextArea;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton feeDetailButton;
    private javax.swing.JButton insertButton;
    private javax.swing.JButton j2011Button;
    private javax.swing.JButton j2012Button;
    private javax.swing.JButton j2013Button;
    private javax.swing.JButton j2014Button;
    private javax.swing.JButton j2015Button;
    private javax.swing.JButton j2016Button;
    private javax.swing.JButton j2017Button;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JInternalFrame jInternalFrame2;
    private javax.swing.JInternalFrame jInternalFrame3;
    private javax.swing.JInternalFrame jInternalFrame4;
    private javax.swing.JInternalFrame jInternalFrame5;
    private javax.swing.JInternalFrame jInternalFrame6;
    private javax.swing.JInternalFrame jInternalFrame7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private javax.swing.JLabel logoutLabel;
    private javax.swing.JButton modifyButton;
    private javax.swing.JButton new_registerButton;
    private javax.swing.JButton payFeeButton;
    private javax.swing.JLabel refreshLabel;
    private javax.swing.JButton speakButton;
    private javax.swing.JButton staffButton;
    private javax.swing.JButton totalAddButton;
    private javax.swing.JButton totalRegdButton;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables
}
