/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyProject1;

import com.sun.glass.events.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.util.Date;
import java.util.Locale;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author SANTOSH
 */
public class Register extends javax.swing.JFrame {

//    int formno=0;
    String name= "";
   // static Connection con=null;
    PreparedStatement pstmt,pstmt3,idpstmt;
    ResultSet rs,genidrs;
    /**
     * Creates new form Register
     */
    public Register() {
        pstmt=null;     
        pstmt3=null;
        idpstmt=null;       
        rs=null;
        genidrs=null;        
        initComponents();
        this.setLocationRelativeTo(null);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        formNoTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        showImageLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        sectionTextField = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        cancleButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        msgLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("FORM NO");

        formNoTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formNoTextFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formNoTextFieldKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("FULL NAME");

        nameTextField.setEditable(false);

        showImageLabel.setBackground(new java.awt.Color(255, 204, 255));
        showImageLabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        showImageLabel.setOpaque(true);

        jLabel6.setFont(new java.awt.Font("Arial", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 255));
        jLabel6.setText("To Register Provide Registration Section :");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("SECTION");

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancleButton.setText("CANCLE");
        cancleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancleButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("YEAR");

        yearLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        yearLabel.setAutoscrolls(true);

        idLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        idLabel.setForeground(new java.awt.Color(255, 46, 2));
        idLabel.setAutoscrolls(true);

        msgLabel.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        msgLabel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sectionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                            .addComponent(yearLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(msgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                                .addComponent(formNoTextField)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(showImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(okButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancleButton)
                        .addGap(32, 32, 32))))
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(formNoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(msgLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(nameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(showImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jLabel6)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(sectionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yearLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(idLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancleButton))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public String generateId(){    
        String sid="",section="";
        try{
            section = sectionTextField.getText().trim().toUpperCase();
            idpstmt=MyLogin.con.prepareStatement("select S_ID from ADMISSION_TABLE where A_YEAR=? and SECTION=? order by S_ID",ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);
            
            idpstmt.setString(1, ""+AdminControl.year);
            idpstmt.setString(2, section);
            genidrs=idpstmt.executeQuery();
            idpstmt.clearParameters();
            
            System.out.println("santosh sahu tata");
                      
            if(genidrs.last()==false){                             
                sid=""+AdminControl.year+""+section+""+1;    
                System.out.println("sir your sid = "+sid);
                 return(sid);        
            }else{
                    String ss=genidrs.getString("S_ID");
                    ss=ss.substring(5);
                int id=Integer.parseInt(ss);
                   id=id+1;
                System.out.println("id = "+id);
                sid=""+AdminControl.year+""+section+""+id;
                
            System.out.println("your full id  is  "+sid);
            return(sid);
            }                                                   
        }   
        catch(Exception e){
            System.out.println(""+e);
        }
        return("_");
    }
    
    private void cancleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancleButtonActionPerformed
        // TODO add your handling code here:
        cancleButton.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        try{
             pstmt.close();         
             pstmt3.close();
             rs.close();
        }
        catch(Exception e){
        }
        Admission ob=new Admission();
        ob.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_cancleButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        // TODO add your handling code here:        
        okButton.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        int check=0;
        String formno="";
          formno=formNoTextField.getText().trim();
    //      check=MyCheck.checkAvailability(formno);    //   will check whether form no exists or not in the case when 
                                     //  user make changes after clicking check button  
        check=MyCheck.checkRegistration(formno);
       if(check==1){           
            int bulb=0;
            String sid="",regd_date="";  
         try{
            pstmt=MyLogin.con.prepareStatement("update ADMISSION_TABLE set S_ID=?,SECTION=?,REGD_DATE=? where FORM_NO=?",ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);                  
            pstmt3=MyLogin.con.prepareStatement("insert into FEE_DETAIL_TABLE(S_ID,PAY1,DATE1,PAY2,DATE2,PAY3,DATE3)values(?,?,?,?,?,?,?)",ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);                             
              
           String section=(sectionTextField.getText().trim()).toUpperCase();
                
            if(section.equals("A")||section.equals("B")||section.equals("C")||section.equals("D")||section.equals("E")){
                
                 sid=generateId();  //Method call
                 
                pstmt.setString(1, sid);
                pstmt.setString(2, section);
                Date date = new Date();
		DateFormat df;
		df = DateFormat.getDateInstance(DateFormat.MEDIUM, Locale.UK);
	
                regd_date=(String)(df.format(date));
                
                pstmt.setString(3,regd_date);
                pstmt.setString(4,formno);
                int i=pstmt.executeUpdate();   //It returns int type whereas executeQuery() returns Statement/PreparedStatement type
                if(i==1){
                    bulb=1;
                    ImageProcessing.myRenameAndMove(formno,name,sid);
                    
                    if(AdminControl.year>=2017){
                        pstmt3.setString(1,sid);
                        pstmt3.setInt(2, 0);
                        pstmt3.setString(3, " ");
                        pstmt3.setInt(4, 0);
                        pstmt3.setString(5, " ");
                        pstmt3.setInt(6, 0);
                        pstmt3.setString(7, " ");
                        i = pstmt3.executeUpdate();
                       if(i==1)
                            System.out.println("inserted into fee_detail_table");
                       else    
                            System.out.println("not inserted into fee_detail_table");
                    }
                    idLabel.setText("Registration Completed, Dear "+name+" Your ID is: "+sid);
                    JOptionPane.showMessageDialog(null, "Please note your registration ID\n\nYour registration ID is: "+sid, "Registration",JOptionPane.INFORMATION_MESSAGE);                    
                }
                else{
                    JOptionPane.showMessageDialog(null, "Registration failed", "Registration", JOptionPane.ERROR_MESSAGE);
                }                                
            }
            else{
                bulb=0;
                JOptionPane.showMessageDialog(null, "Invalid sectin name !!!\n Please provide only A to E ", "Error", JOptionPane.ERROR_MESSAGE);
            }            
      
            pstmt.clearParameters();
            pstmt3.clearParameters();
            pstmt.close();
            pstmt3.close();          
            rs=null;
     
            if(MainPage.option==1&& bulb==1){
                Admission ob=new Admission();
                ob.setVisible(true);
                this.setVisible(false);     
            }   
            else{
                int i=JOptionPane.showConfirmDialog(null, "Stay registering ?","Registration",JOptionPane.OK_OPTION);  
                System.out.println(" i = "+i);
                switch(i){
                    case 0:
                        formNoTextField.setText("");
                        nameTextField.setText("");                    
                        sectionTextField.setText("");
                        showImageLabel.setIcon(null);
                        yearLabel.setText("");
                        break;
                    case 1:
                        MainPage ob=new MainPage();
                        ob.setVisible(true);               
                        this.setVisible(false);
                        break;              
                }               
            }
        }catch(Exception e){JOptionPane.showMessageDialog(null,"INVALID INPUT hai bhaiya "+e,"ERROR",JOptionPane.ERROR_MESSAGE);}
       }
       else{
           JOptionPane.showMessageDialog(null," INVALID INPUT FORM NO DOES NOT MATCH","ERROR",JOptionPane.ERROR_MESSAGE);
       }
       okButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_okButtonActionPerformed

    private void formNoTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formNoTextFieldKeyReleased
        // TODO add your handling code here:
        try{
            String formno=formNoTextField.getText().trim();
            int i=MyCheck.checkRegistration(formno);
            if(i==0){         
              msgLabel.setText("*Form no "+formno+" Already Registered");
              showImageLabel.setIcon(null);
              nameTextField.setText("");
              yearLabel.setText("");
              
            }else{
                msgLabel.setText("");
                
                pstmt=MyLogin.con.prepareStatement("select FIRST_NAME,LAST_NAME from ADMISSION_TABLE where FORM_NO=?",ResultSet.TYPE_SCROLL_SENSITIVE,ResultSet.CONCUR_UPDATABLE);                         
                pstmt.setString(1,formno);
                rs=pstmt.executeQuery();  
                 pstmt.clearParameters();
                if(rs.next()){                                 
                    name=rs.getString(1);
                    name+=" "+rs.getString(2);                
                    nameTextField.setText(name);

                    BufferedImage originalImg=ImageIO.read(new File(".\\test\\Record\\Student_Images\\Admission\\"+name+""+formno+".jpg"));    // to read image do this               
                    ImageIcon icon=new ImageIcon(ImageProcessing.myResize(originalImg,showImageLabel.getWidth(),showImageLabel.getHeight()));
                    showImageLabel.setIcon(icon);                                                 
                    yearLabel.setText(""+AdminControl.year);
                }
            }                
        }catch(NullPointerException e){ }
        catch(Exception e){ }
    }//GEN-LAST:event_formNoTextFieldKeyReleased

    private void formNoTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formNoTextFieldKeyTyped
      char c=evt.getKeyChar();
      if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACKSPACE)||c==KeyEvent.VK_DELETE)){
          getToolkit().beep();
          evt.consume();
      }
    }//GEN-LAST:event_formNoTextFieldKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancleButton;
    private javax.swing.JTextField formNoTextField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel msgLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField sectionTextField;
    private javax.swing.JLabel showImageLabel;
    private javax.swing.JLabel yearLabel;
    // End of variables declaration//GEN-END:variables
}
