/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MyProject1;

import javax.swing.JFrame;

/**
 *
 * @author SANTOSH
 */
public class Section extends javax.swing.JFrame {
    
   static String section;

    /**
     * Creates new form Section
     */
    public Section() {
        section=" ";
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        sectionA_Button = new javax.swing.JButton();
        sectionB_Button = new javax.swing.JButton();
        sectionC_Button = new javax.swing.JButton();
        sectionD_Button = new javax.swing.JButton();
        sectionE_Button = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        mainMenuButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel15.setBackground(new java.awt.Color(0, 0, 102));
        jLabel15.setFont(new java.awt.Font("Century Schoolbook", 1, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("                                                  SELECT A SECTION");
        jLabel15.setOpaque(true);

        sectionA_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyProject1/icons/SECTION_A.png"))); // NOI18N
        sectionA_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectionA_ButtonActionPerformed(evt);
            }
        });

        sectionB_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyProject1/icons/SECTION_B.png"))); // NOI18N
        sectionB_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectionB_ButtonActionPerformed(evt);
            }
        });

        sectionC_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyProject1/icons/SECTION_C.png"))); // NOI18N
        sectionC_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectionC_ButtonActionPerformed(evt);
            }
        });

        sectionD_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyProject1/icons/SECTION_D.png"))); // NOI18N
        sectionD_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectionD_ButtonActionPerformed(evt);
            }
        });

        sectionE_Button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyProject1/icons/SECTION_E.png"))); // NOI18N
        sectionE_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectionE_ButtonActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1380, 100));

        backButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        backButton.setText("<<BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        mainMenuButton.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mainMenuButton.setText("MAIN MENU");
        mainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainMenuButton)
                .addGap(109, 109, 109))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(mainMenuButton))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(sectionA_Button)
                .addGap(79, 79, 79)
                .addComponent(sectionB_Button)
                .addGap(75, 75, 75)
                .addComponent(sectionC_Button)
                .addGap(80, 80, 80)
                .addComponent(sectionD_Button)
                .addGap(82, 82, 82)
                .addComponent(sectionE_Button)
                .addContainerGap(177, Short.MAX_VALUE))
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1378, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sectionA_Button)
                    .addComponent(sectionB_Button)
                    .addComponent(sectionC_Button)
                    .addComponent(sectionD_Button)
                    .addComponent(sectionE_Button))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 411, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        if(MainPage.option==4){
            AdminControl admincontrol=new AdminControl();
            admincontrol.setVisible(true);
            this.setVisible(false);
        }
        else{
            AdminControl.year=0;
        MainPage mainpage=new MainPage();
        mainpage.setVisible(true);
        this.setVisible(false);            
        }
    }//GEN-LAST:event_backButtonActionPerformed

    private void mainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonActionPerformed
        // TODO add your handling code here:
        mainMenuButton.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        AdminControl.year=0;
        MainPage mainpage=new MainPage();
        mainpage.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mainMenuButtonActionPerformed

        private void openingCorrectPage(){
        switch(MainPage.option){
            case 1:
                break;
          /*  case 1:
             /*      Insert insert=new Insert();         // INSERT PAGE 
                   insert.setVisible(true);
                   this.setVisible(false);    */
              /*      Admission admission=new Admission();
                    admission.setVisible(true);
                    this.setVisible(false);
                 break;     */
            case 2:
                   StudentList ob=new StudentList();         // UPDATE PAGE
                   ob.setVisible(true);
                   this.setVisible(false);
                 break; 
            case 3:
                   StudentList delete=new StudentList();         // DELETE PAGE
                   delete.setVisible(true);
                   this.setVisible(false);
                 break;
            case 4:
                   StudentList studentlist=new StudentList();         // SHOW PAGE
                   studentlist.setVisible(true);
                   this.setVisible(false);
                 break; 
        }
    }
    private void sectionA_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sectionA_ButtonActionPerformed
        // TODO add your handling code here:
        sectionA_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        section="A";
        openingCorrectPage();
    }//GEN-LAST:event_sectionA_ButtonActionPerformed

    private void sectionB_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sectionB_ButtonActionPerformed
        // TODO add your handling code here:
        sectionB_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        section="B";
        openingCorrectPage();
    }//GEN-LAST:event_sectionB_ButtonActionPerformed

    private void sectionC_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sectionC_ButtonActionPerformed
        // TODO add your handling code here:
        sectionC_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        section="C";
        openingCorrectPage();
    }//GEN-LAST:event_sectionC_ButtonActionPerformed

    private void sectionD_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sectionD_ButtonActionPerformed
        // TODO add your handling code here:
        sectionD_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        section="D";
        openingCorrectPage();
    }//GEN-LAST:event_sectionD_ButtonActionPerformed

    private void sectionE_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sectionE_ButtonActionPerformed
        // TODO add your handling code here:
        sectionE_Button.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        section="E";
        openingCorrectPage();
    }//GEN-LAST:event_sectionE_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Section().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton mainMenuButton;
    private javax.swing.JButton sectionA_Button;
    private javax.swing.JButton sectionB_Button;
    private javax.swing.JButton sectionC_Button;
    private javax.swing.JButton sectionD_Button;
    private javax.swing.JButton sectionE_Button;
    // End of variables declaration//GEN-END:variables
}
